name: rtype

on:
  push:
    branches:
      - main

env:
 MIRROR_URL: "git@github.com:RayanBn/RType.git"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout le code
      uses: actions/checkout@v2  # Cette étape récupère votre code depuis le dépôt GitHub

    - name: Set up CMake
      run: |
        sudo apt-get update
        sudo apt-get install libx11-dev libxrandr-dev libxcursor-dev libxi-dev libudev-dev libgl1-mesa-dev
        sudo apt-get install ninja-build
        sudo apt-get install -y build-essential
        sudo apt-get install -y cmake
      # Vous pouvez personnaliser cela en fonction de votre système

    - name: Configure le projet avec CMake
      run: |
        git submodule update --init
        cmake -B build
      # Assurez-vous d'être dans le répertoire où se trouve votre fichier CMakeLists.txt

    - name: Construire le projet
      run: cmake --build build  # Assurez-vous d'être dans le répertoire où se trouve votre fichier CMakeLists.txt

    - name: Exécuter les tests unitaires
      run: ./build/unitTest/test  # Assurez-vous d'être dans le répertoire où se trouve votre fichier CMakeLists.txt

    - name: Vérifier les tests réussis
      run: |
        if [ $? -eq 0 ]; then
          echo "Tous les tests ont réussi. Configuration du dépôt distant."
        else
          echo "Certains tests ont échoué. Ne pas effectuer de push."
          exit 1
        fi

    - name: Push vers le dépôt
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote add mirror $MIRROR_URL  # Utilisez la variable d'environnement MIRROR_URL pour spécifier l'URL du dépôt distant
        git push mirror main
