name: rtype

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout le code
      uses: actions/checkout@v2  # Cette étape récupère votre code depuis le dépôt GitHub

    - name: Set up CMake
      run: |
        sudo apt-get update
        pwd
        ls -la
        sudo apt install -y build-essential
        sudo apt-get install -y cmake
      # Vous pouvez personnaliser cela en fonction de votre système

    - name: Configure le projet avec CMake
      run: |
        git submodule update --init
        cmake -B build
      # Assurez-vous d'être dans le répertoire où se trouve votre fichier CMakeLists.txt

    - name: Construire le projet
      run: cmake --build build  # Assurez-vous d'être dans le répertoire où se trouve votre fichier CMakeLists.txt

    - name: Exécuter les tests unitaires
      run: ./build/unitTest/test  # Assurez-vous d'être dans le répertoire où se trouve votre fichier CMakeLists.txt

    - name: Vérifier les tests réussis
      run: |
        if [ $? -eq 0 ]; then
          echo "Tous les tests ont réussi. Configuration du dépôt distant."
        else
          echo "Certains tests ont échoué. Ne pas effectuer de push."
          exit 1
        fi

    - name: Configuration du dépôt distant
      run: git remote add origin https://github.com/RayanBn/RType.git
      # Remplacez <votre_url_de_depot_git> par l'URL de votre dépôt distant

    - name: Push vers le dépôt
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Tests réussis par GitHub Actions"
        git push origin main
